name: Configs tests
on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - master

# Cancel if a newer run is started
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test_all_profiles:
    runs-on: ubuntu-latest
    name: Check if all profiles are tested
    steps:
      - uses: actions/checkout@v4
      - name: Check whether profiles are all tested
        run: python ${GITHUB_WORKSPACE}/bin/cchecker.py ${GITHUB_WORKSPACE}/nfcore_custom.config ${GITHUB_WORKSPACE}/.github/workflows/main.yml

  check_nextflow_config:
    name: Check if nextflow config runs in repository root
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        NXF_VER:
          - 25.04.0
          - latest-everything
    steps:
      - uses: actions/checkout@v4
      - name: Set up Nextflow
        uses: nf-core/setup-nextflow@v2
        with:
          version: ${{ matrix.NXF_VER }}
      - run: nextflow config -show-profiles ${GITHUB_WORKSPACE}

  lint_nextflow_config:
    name: Check if nextflow files are valid with nextflow lint
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        NXF_VER:
          - 25.04.0
          - latest-everything
    steps:
      - uses: actions/checkout@v4
      - name: Set up Nextflow
        uses: nf-core/setup-nextflow@v2
        with:
          version: ${{ matrix.NXF_VER }}
      - run: nextflow lint ${GITHUB_WORKSPACE}

  profile_test:
    runs-on: ubuntu-latest
    name: Run ${{ matrix.profile }} profile
    needs: test_all_profiles
    strategy:
      fail-fast: false
      matrix:
        profile:
          - "dcai_gefion"
          - "ku_cpromegate"
          - "ku_sund_danhead_mod"

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@8df1039502a15bceb9433410b1a100fbe190c53b # v4
        with:
          distribution: "temurin"
          java-version: "17"
      - name: Set up Nextflow
        uses: nf-core/setup-nextflow@v2
        with:
          version: "latest-everything"
      - name: Check ${{ matrix.profile }} profile
        run: nextflow run ${GITHUB_WORKSPACE}/configtest.nf -profile ${{ matrix.profile }}
